version: "4"
name: poc-dotnet-api
services:
  webapi:
    image: mentallygamezsoft/projects-docker-images:poc-dotnet-api-v0.1.3
    pull_policy: always
    container_name: webapi
    networks:
      - poc-dotnet-api-red
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__pocDotnetApi=Server=postgres;Port=5433;Database=pocDotnetApi;User Id=pgadmin;Password=pgadmin
    ports:
      - 5080:8080
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    networks:
      - poc-dotnet-api-red
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
      - PGPORT=5433
    ports:
      - 5433:5433
    # volumes:
    #  - postgresdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgadmin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresdata:

networks:
  poc-dotnet-api-red:
    name: poc-dotnet-api-red